DROP TABLE token IF EXISTS;
DROP TABLE users IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    first_name       VARCHAR(255)            NOT NULL,
    last_name        VARCHAR(255)            NOT NULL,
    login            VARCHAR(255)            NOT NULL,
    password         VARCHAR(255)            NOT NULL,
    role             VARCHAR(255)            NOT NULL,
    state            VARCHAR(255)            NOT NULL

);
CREATE UNIQUE INDEX users_unique_email_idx
    ON USERS (login);


CREATE TABLE token
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    value            VARCHAR(255)            NOT NULL,
    user_id          INTEGER                 NOT NULL,
    CONSTRAINT user_token_value_idx UNIQUE (user_id, value),
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE


);